### ISSUE TITLE
Mniejszość Niemiecka doesn't have a guaranteed seat

### ISSUE THREAD

**Issue by tkgalk** [drastus/sejm-calculator#16]
Sources:
- https://vdg.pl/mniejszosc-niemiecka-nie-ma-zagwarantowanego-miejsca-w-polskim-sejmie/

**Comment by drastus** [comment]
@tkgalk Yes, I'm aware of that. The calculator assumes that the MN committee receives the same percent of support as in the previous election. In 2019 it was 7.9% – in a 12-member constituency a committee with such support nearly always wins one seat, regardless of other committees performance.
I have just updated calculator data to reflect 2023 election. With only 5.37% support MN hardly ever receives a seat. However, it receives one when Lewica and Konfederacja support is very low and TD support is at most moderate.
